// Mocks generated by Mockito 5.4.6 from annotations
// in weather_now/test/data/repositories/weather_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:weather_now/core/utils/connectivity_helper.dart' as _i7;
import 'package:weather_now/data/datasources/local/weather_local_datasource.dart'
    as _i6;
import 'package:weather_now/data/datasources/remote/weather_remote_datasource.dart'
    as _i3;
import 'package:weather_now/data/models/forecast_model.dart' as _i5;
import 'package:weather_now/data/models/weather_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeWeatherModel_0 extends _i1.SmartFake implements _i2.WeatherModel {
  _FakeWeatherModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [WeatherRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherRemoteDataSource extends _i1.Mock
    implements _i3.WeatherRemoteDataSource {
  MockWeatherRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherModel> getCurrentWeather(
    String? city, {
    String? units,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentWeather,
          [city],
          {#units: units},
        ),
        returnValue: _i4.Future<_i2.WeatherModel>.value(_FakeWeatherModel_0(
          this,
          Invocation.method(
            #getCurrentWeather,
            [city],
            {#units: units},
          ),
        )),
      ) as _i4.Future<_i2.WeatherModel>);

  @override
  _i4.Future<List<_i5.ForecastModel>> getForecast(
    String? city, {
    String? units,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getForecast,
          [city],
          {#units: units},
        ),
        returnValue:
            _i4.Future<List<_i5.ForecastModel>>.value(<_i5.ForecastModel>[]),
      ) as _i4.Future<List<_i5.ForecastModel>>);
}

/// A class which mocks [WeatherLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherLocalDataSource extends _i1.Mock
    implements _i6.WeatherLocalDataSource {
  MockWeatherLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherModel?> getCachedWeather(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedWeather,
          [city],
        ),
        returnValue: _i4.Future<_i2.WeatherModel?>.value(),
      ) as _i4.Future<_i2.WeatherModel?>);

  @override
  _i4.Future<void> cacheWeather(_i2.WeatherModel? weather) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheWeather,
          [weather],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.ForecastModel>> getCachedForecast(String? city) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCachedForecast,
          [city],
        ),
        returnValue:
            _i4.Future<List<_i5.ForecastModel>>.value(<_i5.ForecastModel>[]),
      ) as _i4.Future<List<_i5.ForecastModel>>);

  @override
  _i4.Future<void> cacheForecast(
    String? city,
    List<_i5.ForecastModel>? forecast,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheForecast,
          [
            city,
            forecast,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<String>> getFavoriteCities() => (super.noSuchMethod(
        Invocation.method(
          #getFavoriteCities,
          [],
        ),
        returnValue: _i4.Future<List<String>>.value(<String>[]),
      ) as _i4.Future<List<String>>);

  @override
  _i4.Future<void> saveFavoriteCities(List<String>? cities) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFavoriteCities,
          [cities],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getLastCity() => (super.noSuchMethod(
        Invocation.method(
          #getLastCity,
          [],
        ),
        returnValue: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<void> saveLastCity(String? city) => (super.noSuchMethod(
        Invocation.method(
          #saveLastCity,
          [city],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ConnectivityHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityHelper extends _i1.Mock
    implements _i7.ConnectivityHelper {
  MockConnectivityHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<bool> get onConnectivityChanged => (super.noSuchMethod(
        Invocation.getter(#onConnectivityChanged),
        returnValue: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);
}
